version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: taski_management_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: task_management
      restart:
        always
    ports:
      - "5432:5432"
    volumes:
      - "E:/taski/postgres_data:/var/lib/postgresql/data"
    networks:
      - task_network

volumes:
  db_data:

networks:
  task_network:
